export enum ImageEntityType {
  PRODUCT = 'PRODUCT',
  CATEGORY = 'CATEGORY',
  BRAND = 'BRAND',
  SITE_CONFIG = 'SITE_CONFIG',
  USER = 'USER',
  HERO_SLIDE = 'HERO_SLIDE',
  ORDER_LOGISTICS = 'ORDER_LOGISTICS',
  ORDER_CLAIM = 'ORDER_CLAIM',
  ORDER_DELIVERY = 'ORDER_DELIVERY',
  ORDER_REFUND = 'ORDER_REFUND',
}
