import {
  ApplicationConfig,
  importProvidersFrom,
  provideZoneChangeDetection,
} from '@angular/core';
import {
  provideRouter,
  withComponentInputBinding,
  withInMemoryScrolling,
  withViewTransitions,
} from '@angular/router';
import { provideAnimations } from '@angular/platform-browser/animations';
import { routes } from './app.routes';
import { providePrimeNG } from 'primeng/config';
import Aura from '@primeuix/themes/aura';
import {
  ArrowLeft,
  ArrowLeftRight,
  BadgeCheck,
  BookOpen,
  Box,
  Boxes,
  Calendar,
  ChartBar,
  ChartBarStacked,
  ChevronLeft,
  ChevronRight,
  CircleUser,
  CircleUserIcon,
  ClipboardList,
  EllipsisVertical,
  FileCode,
  FileText,
  Folder,
  FolderTree,
  Grid2x2Check,
  HelpCircle,
  Image,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  ListCheck,
  LogOut,
  LucideAngularModule,
  Megaphone,
  Menu,
  MessageSquareQuote,
  MonitorSmartphone,
  MoveLeft,
  MoveRight,
  Package,
  PackageSearch,
  PackageX,
  SearchX,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  Tag,
  Ticket,
  TicketPercent,
  Trash,
  TrendingUp,
  Truck,
  UserCog,
  Users,
  UserSearch,
  Wallet,
  Warehouse,
  X,
  Zap,
} from 'lucide-angular';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { mockInterceptor } from './core/interceptors/mock.interceptor';
import { errorInterceptor } from './core/interceptors/error.interceptor';
import { ErrorHandler } from '@angular/core';
import { GlobalErrorHandler } from './core/errors/global-error-handler';
import { ConfirmationService, MessageService } from 'primeng/api';
import { authInterceptor } from '@core/auth/interceptors/auth.interceptor';
import { provideStore } from '@ngxs/store';
import { withNgxsStoragePlugin, StorageOption } from '@ngxs/storage-plugin';
import { withNgxsReduxDevtoolsPlugin } from '@ngxs/devtools-plugin';
import { withNgxsLoggerPlugin } from '@ngxs/logger-plugin';
import { environment } from '@env/environment';
import { AuthState } from '@core/auth/store/auth.state';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(
      routes,
      withViewTransitions(),
      withComponentInputBinding(),
      withInMemoryScrolling({
        scrollPositionRestoration: 'top',
        anchorScrolling: 'enabled',
      }),
    ),
    provideHttpClient(
      withInterceptors([errorInterceptor, mockInterceptor, authInterceptor]),
    ),
    { provide: ErrorHandler, useClass: GlobalErrorHandler },
    provideAnimations(),
    providePrimeNG({
      theme: {
        preset: Aura,
        options: {
          darkModeSelector: '.none',
        },
      },
      translation: {
        dayNames: [
          'Domingo',
          'Lunes',
          'Martes',
          'Miércoles',
          'Jueves',
          'Viernes',
          'Sábado',
        ],
        dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
        dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
        monthNames: [
          'Enero',
          'Febrero',
          'Marzo',
          'Abril',
          'Mayo',
          'Junio',
          'Julio',
          'Agosto',
          'Septiembre',
          'Octubre',
          'Noviembre',
          'Diciembre',
        ],
        monthNamesShort: [
          'Ene',
          'Feb',
          'Mar',
          'Abr',
          'May',
          'Jun',
          'Jul',
          'Ago',
          'Sep',
          'Oct',
          'Nov',
          'Dic',
        ],
        today: 'Hoy',
        clear: 'Limpiar',
        weekHeader: 'Sem',
        firstDayOfWeek: 1, // ← lunes como primer día
        dateFormat: 'dd/mm/yy',
        accept: 'Aceptar',
        reject: 'Cancelar',
      },
    }),
    importProvidersFrom(
      LucideAngularModule.pick({
        LayoutDashboard,
        Package,
        Tag,
        Users,
        LogOut,
        ChevronRight,
        ChevronLeft,
        Menu,
        X,
        CircleUser,
        CircleUserIcon,
        EllipsisVertical,
        ShoppingBag,
        ShoppingCart,
        Wallet,
        Settings,
        Layers,
        UserCog,
        ShieldCheck,
        TicketPercent,
        MonitorSmartphone,
        MessageSquareQuote,
        Truck,
        BookOpen,
        ClipboardList,
        Megaphone,
        MoveRight,
        MoveLeft,
        ArrowLeft,
        Grid2x2Check,
        Star,
        Warehouse,
        ChartBar,
        FileText,
        LayoutGrid,
        FolderTree,
        BadgeCheck,
        Boxes,
        ArrowLeftRight,
        Ticket,
        FileCode,
        HelpCircle,
        Zap,
        SlidersHorizontal,
        ChartBarStacked,
        TrendingUp,
        UserSearch,
        PackageSearch,
        Box,
        ListCheck,
        Trash,
        Folder,
        PackageX,
        Calendar,
        SearchX,
        Image,
      }),
    ),
    provideStore(
      [AuthState],
      withNgxsStoragePlugin({
        keys: ['adminAuth'], // solo persiste el objeto admin (nombre, email, rol)
        storage: StorageOption.SessionStorage, // sessionStorage: se limpia al cerrar el tab
      }),
      ...(environment.production ? [] : [withNgxsReduxDevtoolsPlugin()]),
      withNgxsLoggerPlugin(),
    ),
    ConfirmationService,
    MessageService,
  ],
};
