import {
  ApplicationConfig,
  importProvidersFrom,
  provideZoneChangeDetection,
} from '@angular/core';
import {
  provideRouter,
  withComponentInputBinding,
  withViewTransitions,
} from '@angular/router';
import { provideAnimations } from '@angular/platform-browser/animations';
import { routes } from './app.routes';
import { providePrimeNG } from 'primeng/config';
import Aura from '@primeuix/themes/aura';
import {
  ArrowLeft,
  BookOpen,
  ChevronLeft,
  ChevronRight,
  CircleUser,
  CircleUserIcon,
  ClipboardList,
  EllipsisVertical,
  Layers,
  LayoutDashboard,
  LogOut,
  LucideAngularModule,
  Megaphone,
  Menu,
  MessageSquareQuote,
  MonitorSmartphone,
  MoveLeft,
  MoveRight,
  Package,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Tag,
  TicketPercent,
  Truck,
  UserCog,
  Users,
  Wallet,
  X,
} from 'lucide-angular';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { mockInterceptor } from './core/interceptors/mock.interceptor';
import { ConfirmationService, MessageService } from 'primeng/api';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withViewTransitions(), withComponentInputBinding()),
    provideHttpClient(withInterceptors([mockInterceptor])),
    provideAnimations(),
    providePrimeNG({
      theme: {
        preset: Aura,
        options: {
          darkModeSelector: '.none',
        },
      },
      translation: {
        dayNames: [
          'Domingo',
          'Lunes',
          'Martes',
          'Miércoles',
          'Jueves',
          'Viernes',
          'Sábado',
        ],
        dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
        dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
        monthNames: [
          'Enero',
          'Febrero',
          'Marzo',
          'Abril',
          'Mayo',
          'Junio',
          'Julio',
          'Agosto',
          'Septiembre',
          'Octubre',
          'Noviembre',
          'Diciembre',
        ],
        monthNamesShort: [
          'Ene',
          'Feb',
          'Mar',
          'Abr',
          'May',
          'Jun',
          'Jul',
          'Ago',
          'Sep',
          'Oct',
          'Nov',
          'Dic',
        ],
        today: 'Hoy',
        clear: 'Limpiar',
        weekHeader: 'Sem',
        firstDayOfWeek: 1, // ← lunes como primer día
        dateFormat: 'dd/mm/yy',
        accept: 'Aceptar',
        reject: 'Cancelar',
      },
    }),
    importProvidersFrom(
      LucideAngularModule.pick({
        LayoutDashboard,
        Package,
        Tag,
        Users,
        LogOut,
        ChevronRight,
        ChevronLeft,
        Menu,
        X,
        CircleUser,
        CircleUserIcon,
        EllipsisVertical,
        ShoppingBag,
        Wallet,
        Settings,
        Layers,
        UserCog,
        ShieldCheck,
        TicketPercent,
        MonitorSmartphone,
        MessageSquareQuote,
        Truck,
        BookOpen,
        ClipboardList,
        Megaphone,
        MoveRight,
        MoveLeft,
        ArrowLeft,
      }),
    ),
    ConfirmationService,
    MessageService,
  ],
};
